In [ ]:
#Building a user-based recommendation model
#Maien Binjonaid

#First - Import useful libraries 

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
#Step 1: Importing data
df = pd.read_csv ('/content/AmazonMoviesandTVRatings.csv')

In [ ]:
#Step 2: Explore the data
print(df)

             user_id  Movie1  Movie2  ...  Movie204  Movie205  Movie206
0     A3R5OBKS7OM2IR     5.0     5.0  ...       NaN       NaN       NaN
1      AH3QC2PC1VTGP     NaN     NaN  ...       NaN       NaN       NaN
2     A3LKP6WPMP9UKX     NaN     NaN  ...       NaN       NaN       NaN
3      AVIY68KEPQ5ZD     NaN     NaN  ...       NaN       NaN       NaN
4     A1CV1WROP5KTTW     NaN     NaN  ...       NaN       NaN       NaN
...              ...     ...     ...  ...       ...       ...       ...
4843  A1IMQ9WMFYKWH5     NaN     NaN  ...       NaN       NaN       5.0
4844  A1KLIKPUF5E88I     NaN     NaN  ...       NaN       NaN       5.0
4845   A5HG6WFZLO10D     NaN     NaN  ...       NaN       NaN       5.0
4846  A3UU690TWXCG1X     NaN     NaN  ...       NaN       NaN       5.0
4847   AI4J762YI6S06     NaN     NaN  ...       NaN       NaN       5.0

[4848 rows x 207 columns]


In [ ]:
#Step 3: check number of nans (no ratings) as it will be useful later on.
df.isnull().sum()

user_id        0
Movie1      4847
Movie2      4847
Movie3      4847
Movie4      4846
            ... 
Movie202    4842
Movie203    4847
Movie204    4840
Movie205    4813
Movie206    4835
Length: 207, dtype: int64

In [ ]:
#Step 4: check the mean and add it as a new row at the end
df.loc['mean'] = df.mean()
print(df)

             user_id  Movie1  Movie2  ...  Movie204  Movie205  Movie206
0     A3R5OBKS7OM2IR     5.0     5.0  ...       NaN       NaN       NaN
1      AH3QC2PC1VTGP     NaN     NaN  ...       NaN       NaN       NaN
2     A3LKP6WPMP9UKX     NaN     NaN  ...       NaN       NaN       NaN
3      AVIY68KEPQ5ZD     NaN     NaN  ...       NaN       NaN       NaN
4     A1CV1WROP5KTTW     NaN     NaN  ...       NaN       NaN       NaN
...              ...     ...     ...  ...       ...       ...       ...
4844  A1KLIKPUF5E88I     NaN     NaN  ...       NaN       NaN  5.000000
4845   A5HG6WFZLO10D     NaN     NaN  ...       NaN       NaN  5.000000
4846  A3UU690TWXCG1X     NaN     NaN  ...       NaN       NaN  5.000000
4847   AI4J762YI6S06     NaN     NaN  ...       NaN       NaN  5.000000
mean             NaN     5.0     5.0  ...     4.375  4.628571  4.923077

[4849 rows x 207 columns]


In [ ]:
#Step 5: I will add a new row to show the number of nans
df.loc['nans']=df.isnull().sum()
print(df)


             user_id  Movie1  Movie2  ...  Movie204     Movie205     Movie206
0     A3R5OBKS7OM2IR     5.0     5.0  ...       NaN          NaN          NaN
1      AH3QC2PC1VTGP     NaN     NaN  ...       NaN          NaN          NaN
2     A3LKP6WPMP9UKX     NaN     NaN  ...       NaN          NaN          NaN
3      AVIY68KEPQ5ZD     NaN     NaN  ...       NaN          NaN          NaN
4     A1CV1WROP5KTTW     NaN     NaN  ...       NaN          NaN          NaN
...              ...     ...     ...  ...       ...          ...          ...
4845   A5HG6WFZLO10D     NaN     NaN  ...       NaN          NaN     5.000000
4846  A3UU690TWXCG1X     NaN     NaN  ...       NaN          NaN     5.000000
4847   AI4J762YI6S06     NaN     NaN  ...       NaN          NaN     5.000000
mean             NaN     5.0     5.0  ...     4.375     4.628571     4.923077
nans               1  4847.0  4847.0  ...  4840.000  4813.000000  4835.000000

[4850 rows x 207 columns]


In [ ]:
#TASK 1: I will sort the data based on the number least nans. 


#Question  1: Which movies have maximum views/ratings?

#Answer to Q1: They are the movies with the least Nans. Based on the following
# They are movies: 127, 140, 16, 103, 29, 91, which have the most number 
# of views/ratings.

dfSortedByNans_1 = df.sort_values(by='nans', axis=1,ascending=True)
dfSortedByNans_1.iloc[-1: , 2:7]


Movie140  Movie16  Movie103  Movie29  Movie91
nans    4270.0   4528.0    4576.0   4605.0   4720.0

In [ ]:
#Question 2: What is the average rating for each movie? Define the top 5 movies 
#with the maximum ratings.
#Answer to Q2: After sorting the data based on the mean (average) rating, 
#we find that many movies received the top rating. As an example, 
# movies: 76, 75, 74, 72, 143.

dfSortedByMean = df.sort_values(by='mean', axis=1, ascending=False)
#print(dfSortedByMean)
dfSortedByMean.iloc[-2:-1 , 2:7]


Movie76  Movie75  Movie74  Movie143  Movie72
mean      5.0      5.0      5.0       5.0      5.0

In [ ]:
#Question 3: Define the top 5 movies with the least audience.
#Answer to Q3: There are many movies with only 1 view. We can see below that 
# movies: 74, 73, 72, 71, 69 are amongst the least viewed, 
# since they contain the most number of Nans.
dfSortedByNans_2 = df.sort_values(by='nans', axis=1, ascending=False)
#print(dfSortedByNans)
dfSortedByNans_2.iloc[-1: , 2:7]

Movie74  Movie73  Movie72  Movie71  Movie69
nans   4847.0   4847.0   4847.0   4847.0   4847.0

Done with Part A. Now off to the recommendation model.

In [ ]:
#import the data again to do some modifications on the dataframe.
df2 = pd.read_csv ('/content/AmazonMoviesandTVRatings.csv')

In [ ]:
print(df2)

             user_id  Movie1  Movie2  ...  Movie204  Movie205  Movie206
0     A3R5OBKS7OM2IR     5.0     5.0  ...       NaN       NaN       NaN
1      AH3QC2PC1VTGP     NaN     NaN  ...       NaN       NaN       NaN
2     A3LKP6WPMP9UKX     NaN     NaN  ...       NaN       NaN       NaN
3      AVIY68KEPQ5ZD     NaN     NaN  ...       NaN       NaN       NaN
4     A1CV1WROP5KTTW     NaN     NaN  ...       NaN       NaN       NaN
...              ...     ...     ...  ...       ...       ...       ...
4843  A1IMQ9WMFYKWH5     NaN     NaN  ...       NaN       NaN       5.0
4844  A1KLIKPUF5E88I     NaN     NaN  ...       NaN       NaN       5.0
4845   A5HG6WFZLO10D     NaN     NaN  ...       NaN       NaN       5.0
4846  A3UU690TWXCG1X     NaN     NaN  ...       NaN       NaN       5.0
4847   AI4J762YI6S06     NaN     NaN  ...       NaN       NaN       5.0

[4848 rows x 207 columns]


In [ ]:
#First I'd like to fill the nans with zeros.
df2=df2.fillna(0)
print(df2)

             user_id  Movie1  Movie2  ...  Movie204  Movie205  Movie206
0     A3R5OBKS7OM2IR     5.0     5.0  ...       0.0       0.0       0.0
1      AH3QC2PC1VTGP     0.0     0.0  ...       0.0       0.0       0.0
2     A3LKP6WPMP9UKX     0.0     0.0  ...       0.0       0.0       0.0
3      AVIY68KEPQ5ZD     0.0     0.0  ...       0.0       0.0       0.0
4     A1CV1WROP5KTTW     0.0     0.0  ...       0.0       0.0       0.0
...              ...     ...     ...  ...       ...       ...       ...
4843  A1IMQ9WMFYKWH5     0.0     0.0  ...       0.0       0.0       5.0
4844  A1KLIKPUF5E88I     0.0     0.0  ...       0.0       0.0       5.0
4845   A5HG6WFZLO10D     0.0     0.0  ...       0.0       0.0       5.0
4846  A3UU690TWXCG1X     0.0     0.0  ...       0.0       0.0       5.0
4847   AI4J762YI6S06     0.0     0.0  ...       0.0       0.0       5.0

[4848 rows x 207 columns]


In [ ]:
#Now I want to turn the movie columns into rows, such that I have the data in
# an easier way to work with. Now I only have three columns.
df3=df2.melt(id_vars=["user_id"], 
        var_name="movie_id", 
        value_name="rating")

In [ ]:
print(df3)

               user_id  movie_id  rating
0       A3R5OBKS7OM2IR    Movie1     5.0
1        AH3QC2PC1VTGP    Movie1     0.0
2       A3LKP6WPMP9UKX    Movie1     0.0
3        AVIY68KEPQ5ZD    Movie1     0.0
4       A1CV1WROP5KTTW    Movie1     0.0
...                ...       ...     ...
998683  A1IMQ9WMFYKWH5  Movie206     5.0
998684  A1KLIKPUF5E88I  Movie206     5.0
998685   A5HG6WFZLO10D  Movie206     5.0
998686  A3UU690TWXCG1X  Movie206     5.0
998687   AI4J762YI6S06  Movie206     5.0

[998688 rows x 3 columns]


In [ ]:
df3.dtypes

user_id      object
movie_id     object
rating      float64
dtype: object

In [ ]:
# I will use the factorize function to assgin each unique user a number 
# to make it easy to work later. 
df3['user_id'] = pd.factorize(df3.user_id)[0]


In [ ]:
print(df3)

        user_id  movie_id  rating
0             0    Movie1     5.0
1             1    Movie1     0.0
2             2    Movie1     0.0
3             3    Movie1     0.0
4             4    Movie1     0.0
...         ...       ...     ...
998683     4843  Movie206     5.0
998684     4844  Movie206     5.0
998685     4845  Movie206     5.0
998686     4846  Movie206     5.0
998687     4847  Movie206     5.0

[998688 rows x 3 columns]


In [ ]:
# I will remove the letters from the movie names also to make things
# easier to work with
df3['movie_id']=df3['movie_id'].str.extract('(\d+)', expand=False)
print(df3)

        user_id movie_id  rating
0             0        1     5.0
1             1        1     0.0
2             2        1     0.0
3             3        1     0.0
4             4        1     0.0
...         ...      ...     ...
998683     4843      206     5.0
998684     4844      206     5.0
998685     4845      206     5.0
998686     4846      206     5.0
998687     4847      206     5.0

[998688 rows x 3 columns]


In [ ]:
df3.dtypes

user_id       int64
movie_id     object
rating      float64
dtype: object

In [ ]:
# I convert everything to integers.
df3["user_id"]=df3["user_id"].astype("int")
df3["movie_id"]=df3["movie_id"].astype("int")
df3["rating"]=df3["rating"].astype("int")

df3.dtypes

user_id     int64
movie_id    int64
rating      int64
dtype: object

In [ ]:
# now we follow the steps we learned in the course
# we divide the data into training and test sets.

from sklearn.model_selection import train_test_split
n_users=df3.user_id.unique().shape[0]
#print(n_users)
n_movies=df3.movie_id.unique().shape[0]
#print(n_movies)
train_data,test_data = train_test_split(df3,test_size=0.25)

In [ ]:
# Now we create a zero matrix for the taining data
# and populate it with the relevant values from the dataframe

train_data_matrix=np.zeros((n_users,n_movies))
#print(train_data_matrix)
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1] = line[3]
train_data_matrix

array([[0., 0., 2., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 5.],
       [0., 0., 0., ..., 0., 0., 5.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# We do the same thing for the test data
test_data_matrix=np.zeros((n_users,n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1] = line[3]
test_data_matrix  

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [5., 5., 0., ..., 0., 0., 0.]])

In [ ]:
# Now we use the cosie similarity matrices for the users 
# and the movies. This enables us to predict values for the
# missing values based on the previous
# ratings on users, and hence completing the task. 

from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix,metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T,metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]
ratings_diff=(train_data_matrix-mean_user_rating)
user_pred=mean_user_rating+user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T
user_pred

array([[-0.00710178, -0.00710178, -0.00710178, ..., -0.00194395,
         0.01806843,  0.0050707 ],
       [-0.01681252, -0.01681252, -0.0163999 , ..., -0.01165469,
         0.00835769, -0.00464004],
       [ 0.00746433,  0.00746433,  0.00787696, ...,  0.01262216,
         0.03263454,  0.01963681],
       ...,
       [ 0.00748031,  0.00748031,  0.00789387, ...,  0.01264987,
         0.03270777,  0.00748031],
       [ 0.00748031,  0.00748031,  0.00789387, ...,  0.01264987,
         0.03270777,  0.00748031],
       [-0.01681252, -0.01681252, -0.0163999 , ..., -0.01165469,
         0.00835769, -0.00464004]])

In [ ]:
#This generates raitings for all movies as required.